### ISSUE TITLE
Relay to another email

### ISSUE THREAD

**Issue by Ndrou** [djfarrelly/MailDev#48]
Hi !

The ability to replace the recipient email address when clicking on "Relay" would be very convenient.

Have a good day !

**Comment by rpaterson** [comment]
Yeah, it sure would be nice.  Need to make this an optional thing though and if no alternate recipient is specified do the current "pure relay" (pass on exactly the same SMTP envelope, etc...)

**Comment by Ndrou** [comment]
:+1:

**Comment by rpaterson** [comment]
Just to clarify, what I would like is something in the web UI that lets the user specify the recipient address per-relay, not e.g. a command-line switch that specifies the recipient address for all relays.  Ideally remember the previously-entered recipient address using a cookie.

**Comment by djfarrelly** [comment]
I think this is a solid idea @Ndro! Also, thanks for the input and cookie idea @rpaterson. I'm traveling and will be quite busy for the next few weeks, so I can't promise right now when I'll be able to hack on this one. If someone submits a PR, I should be able to have a speedy turnaround for merging and publishing. Otherwise I can knock this out in a few weeks when I have time!

**Comment by vialcollet** [comment]
Hi !
Thanks a lot for maildev. It's fantastic. 
I would love being able to have such a "forward" functionality. This would allow to send emails for validation in an easier way than playing with the eml file.

**Comment by vialcollet** [comment]
Hi.
Any idea when we could see this functionality in a future version?
Anyone started looking at it?

**Comment by Ndrou** [comment]
If I have time this week-end I am sending a pull-request with this feature.

**Comment by Ndrou** [comment]
Pull request submitted #126
