### ISSUE TITLE
Add bounce address or return path address to email headers

### ISSUE THREAD

**Issue by npeeples** [djfarrelly/MailDev#99]
Can the headers view get the bounce address added to it? This would be the from address that the smtp server sends initially, the envelope from or also the return path.

I'd be happy to help with pull requests or anything also. A push in the right direction would be helpful ;)

**Comment by djfarrelly** [comment]
Hey @neouser99, for the bounce address are you talking about if using the relay mode? The headers shown in the app are the headers from the originally sent email from whatever app you have send it to MailDev. Since MailDev captures everything there shouldn't be a bounce address (if I'm understanding your idea correctly).

The app is using MailParser (https://github.com/andris9/mailparser) to parse the inbound email ([source](https://github.com/djfarrelly/MailDev/blob/master/lib/mailserver.js#L89-L96)), including the headers. Does this info help at all?

**Comment by oktapodia** [comment]
No answer from the author, I'm closing it
